Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
@testset "Verifying Output" begin
    Random.seed!(0)
    (;d0, d1, L0, L1, c) = Problem()
    alpha, beta, outcomes, costs, trials = simulation(Problem(return_output = true))
    #test alpha â‰ˆ 0.57428237
    #test beta â‰ˆ 0.352510338
    choices = first.(choice.((clamp(beta - eps(), 0, 1),
                              clamp(beta + eps(), 0, 1),
                              clamp(alpha - eps(), 0, 1),
                              clamp(alpha + eps(), 0, 1)),
                              d0, d1, L0, L1, c))
    #test choices[1] == 2
    #test choices[2] â‰  2
    #test choices[3] â‰  1
    #test choices[4] == 1
end
------------------

----- stdout -----
Verifying Output:
----- stdout -----
[91m[1mError During Test[22m[39m at
----- stdout -----
[39m[1mIn[7]:1[22m
  Got exception outside of a @test
  MethodError: no method matching Problem(; return_output::Bool)
  
  [0mClosest candidates are:
  [0m  Problem()[91m got unsupported keyword argument "return_output"[39m
  [0m[90m   @[39m [35mMain[39m [90m[4mIn[6]:36[24m[39m
  [0m  Problem([91m::Any[39m)[91m got unsupported keyword argument "return_output"[39m
  [0m[90m   @[39m [35mMain[39m [90m[4mIn[6]:36[24m[39m
  [0m  Problem([91m::Any[39m, [91m::Any[39m)[91m got unsupported keyword argument "return_output"[39m
  [0m[90m   @[39m [35mMain[39m [90m[4mIn[6]:36[24m[39m
  [0m  ...
  
  Stacktrace:
    [1] [0m[1mmacro expansion[22m
  [90m    @[39m [90m[4mIn[7]:4[24m[39m[90m [inlined][39m
    [2] [0m[1mmacro expansion[22m
  [90m    @[39m [90m/opt/hostedtoolcache/julia/1.9.3/x64/share/julia/stdlib/v1.9/Test/src/[39m[90m[4mTest.jl:1498[24m[39m[90m [inlined][39m
    [3] top-level scope
  [90m    @[39m [90m[4mIn[7]:2[24m[39m
    [4] [0m[1meval[22m
  [90m    @[39m [90m./[39m[90m[4mboot.jl:370[24m[39m[90m [inlined][39m
    [5] [0m[1minclude_string[22m[0m[1m([22m[90mmapexpr[39m::[0mtypeof(REPL.softscope), [90mmod[39m::[0mModule, [90mcode[39m::[0mString, [90mfilename[39m::[0mString[0m[1m)[22m
  [90m    @[39m [90mBase[39m [90m./[39m[90m[4mloading.jl:1903[24m[39m
    [6] [0m[1msoftscope_include_string[22m[0m[1m([22m[90mm[39m::[0mModule, [90mcode[39m::[0mString, [90mfilename[39m::[0mString[0m[1m)[22m
  [90m    @[39m [36mSoftGlobalScope[39m [90m~/.julia/packages/SoftGlobalScope/u4UzH/src/[39m[90m[4mSoftGlobalScope.jl:65[24m[39m
    [7] [0m[1mexecute_request[22m[0m[1m([22m[90msocket[39m::[0mZMQ.Socket, [90mmsg[39m::[0mIJulia.Msg[0m[1m)[22m
  [90m    @[39m [32mIJulia[39m [90m~/.julia/packages/IJulia/Vo51o/src/[39m[90m[4mexecute_request.jl:67[24m[39m
    [8] [0m[1m#invokelatest#2[22m
  [90m    @[39m [90m./[39m[90m[4messentials.jl:819[24m[39m[90m [inlined][39m
    [9] [0m[1minvokelatest[22m
  [90m    @[39m [90m./[39m[90m[4messentials.jl:816[24m[39m[90m [inlined][39m
   [10] [0m[1meventloop[22m[0m[1m([22m[90msocket[39m::[0mZMQ.Socket[0m[1m)[22m
  [90m    @[39m [32mIJulia[39m [90m~/.julia/packages/IJulia/Vo51o/src/[39m[90m[4meventloop.jl:8[24m[39m
   [11] [0m[1m(::IJulia.var"#15#18")[22m[0m[1m([22m[0m[1m)[22m
  [90m    @[39m [32mIJulia[39m [90m./[39m[90m[4mtask.jl:514[24m[39m
[0m[1mTest Summary:    | [22m
----- stdout -----
[91m[1mError  [22m[39m[36m[1mTotal  [22m[39m[0m[1mTime[22m
Verifying Output | [91m    1  [39m[36m    1  [39m[0m2.3s
------------------

[91mSome tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.[39m

Stacktrace:
 [1] finish(ts::Test.DefaultTestSet)
   @ Test /opt/hostedtoolcache/julia/1.9.3/x64/share/julia/stdlib/v1.9/Test/src/Test.jl:1151
 [2] macro expansion
   @ /opt/hostedtoolcache/julia/1.9.3/x64/share/julia/stdlib/v1.9/Test/src/Test.jl:1514 [inlined]
 [3] top-level scope
   @ In[7]:2

